---
- name: Setup the conf/hdfs-site.xml file
  template: src=hdfs-site.xml.j2 dest=/usr/local/hadoop/etc/hadoop/hdfs-site.xml
  tags:
    - config
    - hadoop
- name: Setup the conf/hadoop-env.sh file
  template: src=hadoop-env.sh.j2 dest=/usr/local/hadoop/etc/hadoop/hadoop-env.sh
  tags:
    - config
    - hadoop
- name: Setup the conf/core-site.xml file
  template: src=core-site.xml.j2 dest=/usr/local/hadoop/etc/hadoop/core-site.xml
  tags:
    - config
    - hadoop
- name: Setup the conf/mapred-site.xml file
  template: src=mapred-site.xml.j2 dest=/usr/local/hadoop/etc/hadoop/mapred-site.xml
  tags:
    - config
    - hadoop
- name: Setup the conf/yarn-site.xml file
  template: src=yarn-site.xml.j2 dest=/usr/local/hadoop/etc/hadoop/yarn-site.xml
  tags:
    - config
    - hadoop
- name: Setup the ssh_config file
  template:
      src=ssh_config.j2
      dest=/home/hdu/.ssh/config
      owner=hdu
      group=hadoop
  tags:
    - config
    - hadoop
