---
#- name: install hadoop from remote source
#  unarchive:
#      src=pkg/hadoop-{{hadoop_version}}.tar.gz
#      dest="/usr/local/"
#      remote_src=no
#      owner=hdu
#      group=hadoop
#- name: setup symlink
#  file:
#    src:  /usr/local/hadoop-{{ hadoop_version }}
#    dest: /usr/local/hadoop
#    state: link
- name: create the tmp directory for hdfs
  file: 
    path=/data/hadoop/tmp
    state=directory 
    mode=0750
    owner=hdu
    group=hadoop
- name: Setup the hadoop home
  raw: echo 'export HADOOP_HOME=/usr/local/hadoop' >> /home/hdu/.bashrc
- name: Add the hadoop home to the path
  raw: echo 'export PATH=$PATH:$HADOOP_HOME/bin' >> /home/hdu/.bashrc
