---
# This playbook deploys the whole application stack in this site.

- name: apply common configuration to all nodes
  hosts: all
  remote_user: root
  become: true
  roles:
    - common
    - williamyeh.oracle-java
  vars:
    java_version: 8
    java_set_javahome: true

- name: Configure and deploy the nodes
  hosts: all
  remote_user: root
  become: true
  roles:
    - hadoop
    - spark

- name: Config the master nodes
  hosts: master
  remote_user: root
  become: true
  roles:
    - hadoop_master
    - spark_master
