---
# This playbook deploys the whole application stack in this site.

- name: apply common configuration to all nodes
  hosts: all
  remote_user: root
  become: true
  roles:
    - common

- name: Deploy the hadoop master nodes
  hosts: hadoop_master
  remote_user: root
  become: true
  roles:
    - hadoop_common
    - hadoop

- name: configure and deploy the hadoop slaves nodes
  hosts: hadoop_slave
  remote_user: root
  become: true
  roles:
    - hadoop_common
    - hadoop

- name: Config the hadoop master nodes
  hosts: hadoop_master
  remote_user: root
  become: true
  roles:
    - hadoop_master
