---
- name: Setup the conf/masters file
  template:
    src=masters.j2
    dest=/usr/local/hadoop/etc/hadoop/masters
    owner=hdu
    group=hadoop
- name: Setup the conf/slaves file
  template:
    src=slaves.j2
    dest=/usr/local/hadoop/etc/hadoop/slaves
    owner=hdu
    group=hadoop
