---
- name: Setup the etc/hosts file
  template: src=templates/hosts.j2 dest=/etc/hosts
- name: ensure sshpass is at the latest version
  apt: name=sshpass state=latest
- name: set the hostname
  hostname: name={{hostname}}
